pizza_mama/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

pizza_mama/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizza_mama/pizza_mama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('menu/', include('menu.urls')),
]

pizza_mama/main/models.py
from django.db import models

# Create your models here.

pizza_mama/menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)
    
    def __str__(self):
        return self.nom

pizza_mama/main/views.py
from django.shortcuts import render
# Create your views here.






def index(request):
    return render(request, 'main/index.html')

pizza_mama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza
# Create your views here.






def index(request):
    # pizzas = Pizza.objects.all()
    # pizza_names_and_price = [pizza.nom + " Prix : " + str(pizza.prix) + "€" for pizza in pizzas]
    # pizza_names_and_price_str = ", ".join(pizza_names_and_price)
    # return HttpResponse("Les Pizzas : " + pizza_names_and_price_str)
    pizzas = Pizza.objects.all()
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizza_mama/main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Voir le menu</a>
    </div>
</body>
</html>

pizza_mama/menu/templates/menu/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
</head>
<body>
    <a href="{% url 'main:index' %}"><img id="logo" src="{% static 'menu/img/small_logo.png' %}"></a>
    <h1>Nos Pizzas</h1>

    <section class="menu_list">
        {% for pizza in pizzas %}
            <div class="menu_item">
                <h2 class="menu_title"></span>{{pizza.nom}} : <span class="menu_price">{{pizza.prix}} €</span></h2>
                <span class="menu_ingredients">{{pizza.ingredients}}</span>
                {% if pizza.vegetarienne %}
                <span class="menu_vegan">100% vegan</span>
                {% endif %}
            </div>
        {% endfor %}
    </section>
</body>
</html>